# Understanding the problem space

El objetivo de este documento es realizar la primera tarea del módulo 2, Understanding the problem space.

Voy a repartir el análisis en las siguientes partes:

1. Cargar los datos extraidos a través de AWS CLI. Los he guardado en un directorio dentro de mi WSL llamado `data` 
2. Hacer un `head()` y un `describe()` de los 5 datasets.

In [24]:
import pandas as pd

In [25]:
df_users = pd.read_parquet('~/data/users.parquet', engine='pyarrow')
df_orders = pd.read_parquet('~/data/orders.parquet', engine='pyarrow')
df_abandoned_carts = pd.read_parquet('~/data/abandoned_carts.parquet', engine='pyarrow')
df_inventory = pd.read_parquet('~/data/inventory.parquet', engine='pyarrow')
df_regulars = pd.read_parquet('~/data/regulars.parquet', engine='pyarrow')

In [50]:
def df_info_and_head(df):
    df.info()
    display(df.head())
    display(df.describe())

In [51]:
df_info_and_head(df_users)

<class 'pandas.core.frame.DataFrame'>
Index: 4983 entries, 2160 to 3360
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                4983 non-null   object
 1   user_segment           4983 non-null   object
 2   user_nuts1             4932 non-null   object
 3   first_ordered_at       4983 non-null   object
 4   customer_cohort_month  4983 non-null   object
 5   count_people           325 non-null    float64
 6   count_adults           325 non-null    float64
 7   count_children         325 non-null    float64
 8   count_babies           325 non-null    float64
 9   count_pets             325 non-null    float64
dtypes: float64(5), object(5)
memory usage: 428.2+ KB

,user_id,user_segment,user_nuts1,first_ordered_at,customer_cohort_month,count_people,count_adults,count_children,count_babies,count_pets
2160,0e823a42e107461379e5b5613b7aa00537a72e1b0eaa7a...,Top Up,UKH,2021-05-08 13:33:49,2021-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN
1123,15768ced9bed648f745a7aa566a8895f7a73b9a47c1d4f...,Top Up,UKJ,2021-11-17 16:30:20,2021-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN
1958,33e0cb6eacea0775e34adbaa2c1dec16b9d6484e6b9324...,Top Up,UKD,2022-03-09 23:12:25,2022-03-01 00:00:00,NaN,NaN,NaN,NaN,NaN
675,57ca7591dc79825df0cecc4836a58e6062454555c86c35...,Top Up,UKI,2021-04-23 16:29:02,2021-04-01 00:00:00,NaN,NaN,NaN,NaN,NaN
4694,085d8e598139ce6fc9f75d9de97960fa9e1457b409ec00...,Top Up,UKJ,2021-11-02 13:50:06,2021-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN

       count_people  count_adults  count_children  count_babies  count_pets
count    325.000000    325.000000      325.000000    325.000000  325.000000
mean       2.787692      2.003077        0.707692      0.076923    0.636923
std        1.365753      0.869577        1.026246      0.289086    0.995603
min        0.000000      0.000000        0.000000      0.000000    0.000000
25%        2.000000      2.000000        0.000000      0.000000    0.000000
50%        3.000000      2.000000        0.000000      0.000000    0.000000
75%        4.000000      2.000000        1.000000      0.000000    1.000000
max        8.000000      7.000000        6.000000      2.000000    6.000000

In [49]:
8773/4983

1.7605859923740719

## Users

Tenemos las siguientes columnas:

- `user_id`: Identificador del usuario
    - Hay clientes duplicados?
- `user_segment`: Variable categórica con baja cardinalidad: Top Up o Proposition
    - Que representa cada una de las cosas?
    - Este dato esta relacionado con la fecha en la que aparece el cliente? De que depende?
    - Creo que va a depender de si el cliente realiza muchas compras o no. Cómo puedo hacer esto?
- `user_nuts1`: Localización del cliente. Está indicado por la región nuts1. En este link más info https://en.wikipedia.org/wiki/First-level_NUTS_of_the_European_Union
- `first_ordered_at`: 
- `customer_cohort_month`:

Solo tiene tenemos datos del 6.52% de los clientes para estas variables:
- `count_people`
- `count_adults`
- `count_children`
- `count_babies`
- `count_pets`

¿ Porque tenemos pocas entradas de estas variables?
Hipótesis:
- Los datos se empezaron a recoger para una fecha concreta: En este caso, las entradas deberían estar a partir de una fecha concreta.
- Los datos se proporcionan de manera voluntaria

¿Cómo ha evolucionado el número de clientes a lo largo del tiempo?
De es

Segmentación de clientes? Puede venir bien para entender los tipos de customers que puede haber.

In [44]:
df_users.groupby('user_segment').user_id.nunique()

user_segment
Proposition    2340
Top Up         2643
Name: user_id, dtype: int64